# Generated by Django 3.2 on 2024-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BindingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.TextField()),
                ('invite_cod', models.TextField()),
            ],
            options={
                'db_table': 'binding_invite',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.TextField()),
                ('status_auth', models.BooleanField()),
                ('personal_invite', models.TextField()),
                ('temporary_code', models.TextField()),
                ('activate_invait', models.BooleanField()),
                ('telephone_invait', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
