version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    restart: always
    container_name: app
    volumes:
      - ${PWD}:/ReferalApp
    ports:
      - "8000:8000"
    
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=referalapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always  
    ports:
      - 8181:8080
      
volumes:
  postgres_data: